# Generated by Django 4.2 on 2023-04-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropamodel',
            name='hasStock',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
