# Generated by Django 4.2 on 2023-04-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0002_ropamodel_hasstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropamodel',
            name='back_picture',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropamodel',
            name='front_picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
