# Generated by Django 4.2 on 2023-04-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0003_ropamodel_back_picture_ropamodel_front_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropamodel',
            name='back_picture',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ropamodel',
            name='front_picture',
            field=models.CharField(max_length=200),
        ),
    ]
