# Generated by Django 4.2 on 2023-04-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0004_alter_ropamodel_back_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropamodel',
            name='back_picture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ropamodel',
            name='front_picture',
            field=models.IntegerField(),
        ),
    ]
