# Generated by Django 4.2 on 2023-04-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0005_alter_ropamodel_back_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropamodel',
            old_name='back_picture',
            new_name='imgBack',
        ),
        migrations.RenameField(
            model_name='ropamodel',
            old_name='front_picture',
            new_name='imgFront',
        ),
    ]
