# Generated by Django 4.2 on 2023-04-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0007_remove_ropamodel_imgback_remove_ropamodel_imgfront_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropamodel',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
