# Generated by Django 4.2 on 2023-04-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmodel',
            name='image',
            field=models.ImageField(default='imagen', upload_to=''),
            preserve_default=False,
        ),
    ]
