# Generated by Django 4.2 on 2023-04-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imagesmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='imgBack',
            field=models.ImageField(default='equisde', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='imgFront',
            field=models.ImageField(default='eeee', upload_to=''),
            preserve_default=False,
        ),
    ]
